version: "3.4"
services:

  hipotalks_app:
    build:
      context: .
      target: application
    image: hipotalks_app
    environment:
      - DJANGO_SETTINGS_MODULE=hipotalks.settings.production
    depends_on:
      - hipotalks_postgres
    command: gunicorn --config conf/gunicorn-production.conf.py hipotalks.wsgi
    ports:
      - "8000:8000"
    tty: true

  nginx:
    image: nginx:1.15.7
    ports:
      - "80:80"
    depends_on:
      - hipotalks_app
    container_name: hipotalks_nginx
    volumes:
      - ./conf/nginx_production.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/:/hipotalks/frontend/
    restart: unless-stopped

  hipotalks_postgres:
    image: mdillon/postgis:11
    environment:
      - POSTGRES_DB=hipotalks_production
      - POSTGRES_USER=hipotalks_dbu
      - POSTGRES_PASSWORD_DEV=wlkrtjesrlkna
    container_name: hipotalks_postgres
    volumes:
      - ".data/db:/var/lib/postgresql/data"
    ports:
     - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --quiet || exit 1"]
      interval: 1m
      timeout: 30s
      retries: 10
      start_period: 40s
