# Generated by Django 2.2.4 on 2019-09-26 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hipo_django_core.models
import hipo_django_core.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigIntegerField(default=hipo_django_core.utils.generate_unique_id, editable=False, primary_key=True, serialize=False)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blacklist', to='events.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blacklist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(hipo_django_core.models.LogEntryMixin, models.Model),
        ),
    ]
