# Generated by Django 2.2.4 on 2019-09-26 09:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='canceled_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='canceled_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
