# Generated by Django 2.2.4 on 2019-09-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190926_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
