# Generated by Django 2.2.4 on 2019-09-26 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hipo_django_core.models
import hipo_django_core.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigIntegerField(default=hipo_django_core.utils.generate_unique_id, editable=False, primary_key=True, serialize=False)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slide_link', models.URLField(blank=True, max_length=255, null=True)),
                ('video_link', models.URLField(blank=True, max_length=255, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presentations', to='events.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presentations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Presentation',
                'verbose_name_plural': 'Presentations',
                'ordering': ('creation_datetime',),
            },
            bases=(hipo_django_core.models.LogEntryMixin, models.Model),
        ),
    ]
