# Generated by Django 2.2.4 on 2019-11-01 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hipo_django_core.models
import hipo_django_core.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('presentations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigIntegerField(default=hipo_django_core.utils.generate_unique_id, editable=False, primary_key=True, serialize=False)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('did-the-presentation', 'Did the presentation'), ('mucbir', 'Mucbir'), ('fail', 'Fail'), (None, 'None')], default=None, max_length=255, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='events.Event')),
                ('presentation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slot', to='presentations.Presentation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Slot',
                'verbose_name_plural': 'Slots',
                'ordering': ('event__date',),
            },
            bases=(hipo_django_core.models.LogEntryMixin, models.Model),
        ),
    ]
